name: ssi
description: >-
  Affinidi SSI library for Dart provides a comprehensive suite of tools and
  libraries for implementing Self-Sovereign Identity (SSI) solutions.
version: 4.0.2
resolution: workspace
repository: https://github.com/affinidi/affinidi-ssi-dart
environment:
  sdk: ^3.6.0
dependencies:
  archive: ^4.0.7
  base_codecs: ^1.0.1
  bip32_plus: ^1.0.0
  crypto: ^3.0.3
  cryptography: ^2.7.0
  dart_jsonwebtoken: ^3.2.0
  ecdsa: ^0.1.2
  ed25519_edwards: ^0.3.1
  ed25519_hd_key: ^2.3.0
  elliptic: ^0.3.11
  http: ^1.4.0
  json_ld_processor: ^1.0.4
  meta: ^1.15.0
  pointycastle: ^4.0.0
  pqcrypto: ^0.3.1
  selective_disclosure_jwt: ^1.1.0
  x25519: ^0.1.2

workspace:
  - example/dids/didwebvh
dev_dependencies:
  aws_kms_api: ^2.0.0
  aws_signature_v4: ^0.6.4
  coverage: ^1.11.1
  dart_flutter_team_lints: ^3.2.1
  melos: ^8.5.0
  shared_aws_api: ^2.0.2
  test: ^1.24.0

topics:
  - ssi
  - cryptography
  - did

command:
  version:
    changelogCommitBodies:
      include: true
      onlyBreaking: false

melos:
  name: ssi
  useRootAsPackage: true
  scripts:
    fix:
      exec: dart fix --apply
      concurrency: 4
      failFast: true
      noSelect: true
      packageFilters:
        includePrivatePackages: false
        diff: origin/main
    analyze:
      exec: dart analyze .
      concurrency: 4
      failFast: true
      noSelect: true
      packageFilters:
        includePrivatePackages: false
        diff: origin/main
    test:
      run: |
        melos run test-dart
    test-dart:
      description: Run tests in each dart package
      exec: dart run coverage:test_with_coverage
      dirExists: test
      concurrency: 4
      failFast: true
      noSelect: true
      packageFilters:
        private: false
        ignore:
          - "*_example*"
